### ISSUE TITLE
Wireframe a single post

### ISSUE THREAD

**Issue by alicedilemma** [girlcodeakl/girlcode-2019-term2#16]
_This task is timeboxed for 20 minutes_ 

Draw up a wireframe (on paper or try a tool like figma) for a single post.

It will need to include:
- [x] the title (name of the cafe)
- [x] A picture
- [x] the author / user who poster the message
- [x] the time it was posted
- [x] The poll question
- [x] 4 options that people can vote for

**Comment by sparkly123** [comment]
Have completed.
